# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DailyPlanner
 pod 'McPicker', '~> 3.0.0'
 pod 'SwiftGifOrigin', '~> 1.7.0'
 pod 'SnackBar.swift'
 pod 'Material', '~> 3.1.0'


end
